# -*- coding: utf-8 -*-
"""TASK 4 (SENTIMENT ANALYSIS) INTERSHIP CodeAlpha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gucB2MQBOxS2vUzCYsAuPAX2e5mrVxdV
"""

import kagglehub
import pandas as pd
import os
path = kagglehub.dataset_download("snap/amazon-fine-food-reviews")
csv_file_path = os.path.join(path, 'Reviews.csv')
df = pd.read_csv(csv_file_path)
display(df.head())

"""### Sentiment Analysis

To classify the text data, we'll first define sentiment categories based on the `Score` column. Typically:
- Scores of 4 or 5 are considered positive.
- Scores of 1 or 2 are considered negative.
- A score of 3 is considered neutral.

After assigning sentiment labels, we'll preprocess the text data (e.g., `Text` and `Summary` columns) and then use a machine learning or deep learning model for classification.
"""

print("Distribution of review scores:")
display(df['Score'].value_counts().sort_index())
def get_sentiment(score):
    if score > 3:
        return 'Positive'
    elif score < 3:
        return 'Negative'
    else:
        return 'Neutral'
df['Sentiment'] = df['Score'].apply(get_sentiment)
print("\nDistribution of sentiment:")
display(df['Sentiment'].value_counts())

"""Now that we have sentiment labels, the next steps typically involve:

1.  **Text Preprocessing**: Cleaning and preparing the `Text` and/or `Summary` columns. This includes tasks like:
    *   Removing punctuation, numbers, and special characters.
    *   Converting text to lowercase.
    *   Tokenization (splitting text into words).
    *   Removing stop words (common words like 'the', 'a', 'is').
    *   Lemmatization or stemming (reducing words to their base form).

2.  **Feature Extraction**: Converting the preprocessed text into numerical features that a machine learning model can understand. Common techniques include:
    *   Bag-of-Words (BoW) / TF-IDF.
    *   Word Embeddings (e.g., Word2Vec, GloVe).

3.  **Model Training**: Training a classification model (e.g., Logistic Regression, Naive Bayes, Support Vector Machines, or deep learning models like LSTMs/Transformers) on the preprocessed and featurized text data to predict the sentiment.

### Text Preprocessing: Cleaning the `Text` column

For simplicity, we will perform the following steps:
1.  Convert text to lowercase.
2.  Remove punctuation.
3.  Remove common English stop words (words like 'the', 'a', 'is' that don't add much meaning for sentiment analysis).
"""

import nltk
from nltk.corpus import stopwords
import string
try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords')

stop_words = set(stopwords.words('english'))
def clean_text(text):
    text = str(text).lower()
    text = ''.join([char for char in text if char not in string.punctuation])
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text
df['cleaned_text'] = df['Text'].apply(clean_text)
print("Original vs. Cleaned Text Samples:")
for i in range(5):
    print(f"\nOriginal: {df['Text'].iloc[i]}")
    print(f"Cleaned:  {df['cleaned_text'].iloc[i]}")

"""After cleaning the text, the next step is to convert this text data into numerical features that a machine learning model can process. A simple and common method is using **TF-IDF (Term Frequency-Inverse Document Frequency)**, which reflects how important a word is to a document in a collection or corpus.

Once the text is converted into numerical features, we can then train a simple classification model, such as **Logistic Regression** or **Naive Bayes**, to predict sentiment.

### Feature Extraction: TF-IDF Vectorization

We will use `TfidfVectorizer` from `sklearn.feature_extraction.text` to convert our `cleaned_text` into numerical feature vectors. This process assigns a weight to each word, reflecting its importance in the document and the corpus.
"""

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=5000, min_df=5, max_df=0.7)
X = tfidf_vectorizer.fit_transform(df['cleaned_text'])
y = df['Sentiment']

print(f"Shape of TF-IDF features (X): {X.shape}")
print(f"Shape of sentiment labels (y): {y.shape}")

"""### Model Training: Logistic Regression

Now that we have numerical features, we can train a classification model. We'll split our data into training and testing sets, train a `LogisticRegression` model, and then evaluate its performance.
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")
log_reg_model = LogisticRegression(max_iter=1000, solver='liblinear', random_state=42)
log_reg_model.fit(X_train, y_train)
y_pred = log_reg_model.predict(X_test)
print("\nModel Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

"""### Emotion Detection using `text2emotion`

While sentiment analysis categorizes text as positive, negative, or neutral, emotion detection aims to identify more specific human emotions like happiness, sadness, anger, fear, or surprise. We'll use the `text2emotion` library, which provides a simple way to extract these emotions based on a pre-defined lexicon.

First, we need to install the library and download its required NLTK resources.
"""

import sys
import importlib
sys.setrecursionlimit(3000)
if 'emoji' in sys.modules:
    del sys.modules['emoji']
if 'text2emotion' in sys.modules:
    del sys.modules['text2emotion']
!{sys.executable} -m pip uninstall -y emoji
!{sys.executable} -m pip install emoji==1.7.0
!{sys.executable} -m pip install text2emotion
import nltk
try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')
try:
    nltk.data.find('corpora/omw-1.4')
except LookupError:
    nltk.download('omw-1.4')
import text2emotion as te
import pandas as pd

"""Now that `text2emotion` is installed, we can import it and apply it to our `cleaned_text` column. The library returns a dictionary of emotions and their scores for each text. We'll extract the primary emotion or a set of dominant emotions."""

def get_emotions(text):
    if pd.isna(text) or not isinstance(text, str) or text.strip() == '':
        return {'Happy': 0, 'Angry': 0, 'Surprise': 0, 'Sad': 0, 'Fear': 0}
    try:
        return te.get_emotion(text)
    except Exception as e:

        print(f"Error processing text: {text[:50]}... Error: {e}")
        return {'Happy': 0, 'Angry': 0, 'Surprise': 0, 'Sad': 0, 'Fear': 0}

print("Extracting emotions... This might take a while for a large dataset.")
df['emotions'] = df['cleaned_text'].apply(get_emotions)

emotion_df = pd.json_normalize(df['emotions'])
df = pd.concat([df, emotion_df], axis=1)

print("Emotion extraction complete. Displaying first 5 rows with emotion scores:")
display(df[['cleaned_text', 'Happy', 'Angry', 'Surprise', 'Sad', 'Fear']].head())

"""Now, let's look at the overall distribution of these emotions across the entire dataset to understand which emotions are most prevalent in the reviews."""

import matplotlib.pyplot as plt
import seaborn as sns

sentiment_counts = df['Sentiment'].value_counts(normalize=True)

print("Overall Sentiment Distribution (Proportions):")
display(sentiment_counts)

plt.figure(figsize=(8, 5))
sns.barplot(x=sentiment_counts.index, y=sentiment_counts.values, palette='coolwarm')
plt.title('Overall Sentiment Distribution in Amazon Food Reviews')
plt.xlabel('Sentiment')
plt.ylabel('Proportion')
plt.show()

print("\nNote: The `text2emotion` library encountered persistent recursion errors and could not reliably extract specific emotions (Happy, Angry, Surprise, Sad, Fear) from this large dataset. Therefore, we are visualizing the sentiment distribution instead, which was successfully computed.")

