# -*- coding: utf-8 -*-
"""TASK 02 ( EXPORATORY DATA ANAYLSIS)   (INTERSHIP CodeAlpha)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Rin8xnO40tYoinq--wt6--act5FJsto
"""

import pandas as pd

df = pd.read_csv('/content/Telco-Customer-Churn.csv')
display(df.head())

"""### 10 Meaningful Questions for Data Understanding:

1.  **What is the overall churn rate in this dataset?** (i.e., What percentage of customers have churned?)
2.  **What is the distribution of customer demographics?** (e.g., gender, SeniorCitizen, Partner, Dependents)
3.  **How do different contract types influence churn?** (e.g., Month-to-month, One year, Two year)
4.  **Are there specific internet service types or additional services (e.g., OnlineSecurity, TechSupport) that are more prone to churn?**
5.  **What is the distribution of `Tenure` (months a customer has stayed with the company)? Is there a relationship between `Tenure` and `Churn`?
6.  **How do `MonthlyCharges` and `TotalCharges` vary across different customer segments and churn status?** (Are higher charges associated with higher or lower churn?)
7.  **Do customers with multiple lines or fiber optic internet service have different churn patterns compared to others?**
8.  **Are there any missing values or inconsistencies in the `TotalCharges` column, given it's currently an object type?** (This might require data cleaning).
9.  **What payment methods are most commonly used by customers who churn?**
10. **Is there any noticeable difference in churn rates between male and female customers, or between senior citizens and non-senior citizens?**

### Question 1: What is the overall churn rate in this dataset?
"""

# Convert 'Churn' column to numeric (0 for No, 1 for Yes)
df['Churn_Numeric'] = df['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

# Calculate the churn rate
churn_rate = df['Churn_Numeric'].mean() * 100

print(f"Overall Churn Rate: {churn_rate:.2f}%")

"""### Question 2: What is the distribution of customer demographics?

Let's analyze the distribution of `gender`.
"""

gender_distribution = df['gender'].value_counts()
print("Gender Distribution:")
display(gender_distribution)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6, 4))
sns.countplot(x='gender', data=df, palette='viridis')
plt.title('Distribution of Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Customers')
plt.show()

"""Let's analyze the distribution of `SeniorCitizen`."""

senior_citizen_distribution = df['SeniorCitizen'].value_counts()
print("Senior Citizen Distribution:")
display(senior_citizen_distribution)

plt.figure(figsize=(6, 4))
sns.countplot(x='SeniorCitizen', data=df, palette='pastel')
plt.title('Distribution of Senior Citizens')
plt.xlabel('Senior Citizen (0: No, 1: Yes)')
plt.ylabel('Number of Customers')
plt.xticks(ticks=[0, 1], labels=['No', 'Yes'])
plt.show()

"""Let's analyze the distribution of `Partner`."""

partner_distribution = df['Partner'].value_counts()
print("Partner Distribution:")
display(partner_distribution)

plt.figure(figsize=(6, 4))
sns.countplot(x='Partner', data=df, palette='cubehelix')
plt.title('Distribution of Customers with Partners')
plt.xlabel('Partner')
plt.ylabel('Number of Customers')
plt.show()

"""Let's analyze the distribution of `Dependents`."""

dependents_distribution = df['Dependents'].value_counts()
print("Dependents Distribution:")
display(dependents_distribution)

plt.figure(figsize=(6, 4))
sns.countplot(x='Dependents', data=df, palette='magma')
plt.title('Distribution of Customers with Dependents')
plt.xlabel('Dependents')
plt.ylabel('Number of Customers')
plt.show()

"""### Question 3: How do different contract types influence churn?"""

contract_churn = df.groupby('Contract')['Churn_Numeric'].mean().reset_index()
contract_churn['Churn_Rate'] = contract_churn['Churn_Numeric'] * 100
print("Churn Rate by Contract Type:")
display(contract_churn)

plt.figure(figsize=(8, 5))
sns.barplot(x='Contract', y='Churn_Rate', data=contract_churn, palette='viridis')
plt.title('Churn Rate by Contract Type')
plt.xlabel('Contract Type')
plt.ylabel('Churn Rate (%)')
plt.ylim(0, 100) # Ensure y-axis is from 0 to 100 for percentage
plt.show()

"""### Question 4: Are there specific internet service types or additional services (e.g., OnlineSecurity, TechSupport) that are more prone to churn?

Let's analyze the churn rate by `InternetService` type.
"""

internet_service_churn = df.groupby('InternetService')['Churn_Numeric'].mean().reset_index()
internet_service_churn['Churn_Rate'] = internet_service_churn['Churn_Numeric'] * 100
print("Churn Rate by Internet Service Type:")
display(internet_service_churn)

plt.figure(figsize=(8, 5))
sns.barplot(x='InternetService', y='Churn_Rate', data=internet_service_churn, palette='coolwarm')
plt.title('Churn Rate by Internet Service Type')
plt.xlabel('Internet Service Type')
plt.ylabel('Churn Rate (%)')
plt.ylim(0, 100)
plt.show()

"""Let's analyze the churn rate by `OnlineSecurity`."""

online_security_churn = df.groupby('OnlineSecurity')['Churn_Numeric'].mean().reset_index()
online_security_churn['Churn_Rate'] = online_security_churn['Churn_Numeric'] * 100
print("Churn Rate by OnlineSecurity:")
display(online_security_churn)

plt.figure(figsize=(8, 5))
sns.barplot(x='OnlineSecurity', y='Churn_Rate', data=online_security_churn, palette='plasma')
plt.title('Churn Rate by Online Security')
plt.xlabel('Online Security')
plt.ylabel('Churn Rate (%)')
plt.ylim(0, 100)
plt.show()

"""Let's analyze the churn rate by `TechSupport`."""

tech_support_churn = df.groupby('TechSupport')['Churn_Numeric'].mean().reset_index()
tech_support_churn['Churn_Rate'] = tech_support_churn['Churn_Numeric'] * 100
print("Churn Rate by TechSupport:")
display(tech_support_churn)

plt.figure(figsize=(8, 5))
sns.barplot(x='TechSupport', y='Churn_Rate', data=tech_support_churn, palette='rocket')
plt.title('Churn Rate by Tech Support')
plt.xlabel('Tech Support')
plt.ylabel('Churn Rate (%)')
plt.ylim(0, 100)
plt.show()

"""### Question 5: What is the distribution of `Tenure` (months a customer has stayed with the company)? Is there a relationship between `Tenure` and `Churn`?

Let's first examine the distribution of `Tenure`.
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['tenure'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Customer Tenure')
plt.xlabel('Tenure (Months)')
plt.ylabel('Number of Customers')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""Now, let's explore the relationship between `Tenure` and `Churn`."""

plt.figure(figsize=(10, 6))
sns.boxplot(x='Churn', y='tenure', data=df, palette='coolwarm')
plt.title('Tenure Distribution by Churn Status')
plt.xlabel('Churn')
plt.ylabel('Tenure (Months)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.kdeplot(data=df, x='tenure', hue='Churn', fill=True, common_norm=False, palette='viridis')
plt.title('Density Plot of Tenure by Churn Status')
plt.xlabel('Tenure (Months)')
plt.ylabel('Density')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### Question 6: How do `MonthlyCharges` and `TotalCharges` vary across different customer segments and churn status? (Are higher charges associated with higher or lower churn?)

Let's start by examining `MonthlyCharges` in relation to churn.
"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='Churn', y='MonthlyCharges', data=df, palette='GnBu')
plt.title('Monthly Charges Distribution by Churn Status')
plt.xlabel('Churn')
plt.ylabel('Monthly Charges')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.kdeplot(data=df, x='MonthlyCharges', hue='Churn', fill=True, common_norm=False, palette='viridis')
plt.title('Density Plot of Monthly Charges by Churn Status')
plt.xlabel('Monthly Charges')
plt.ylabel('Density')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""Next, let's analyze `TotalCharges` in relation to churn. First, we need to convert `TotalCharges` to a numeric type, as it contains non-numeric values (likely empty strings or spaces) and might be stored as an object."""

# Convert TotalCharges to numeric, coercing errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Check for missing values introduced by coercion
missing_total_charges = df['TotalCharges'].isnull().sum()
print(f"Number of missing values in TotalCharges after conversion: {missing_total_charges}")

# Fill missing values with the median for now, or consider dropping rows if appropriate
# For this analysis, filling with median is a reasonable approach to retain data
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

print("Distribution of Total Charges:")
plt.figure(figsize=(10, 6))
sns.histplot(df['TotalCharges'], bins=30, kde=True, color='purple')
plt.title('Distribution of Total Charges')
plt.xlabel('Total Charges')
plt.ylabel('Number of Customers')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print("Total Charges Distribution by Churn Status:")
plt.figure(figsize=(10, 6))
sns.boxplot(x='Churn', y='TotalCharges', data=df, palette='YlGnBu')
plt.title('Total Charges Distribution by Churn Status')
plt.xlabel('Churn')
plt.ylabel('Total Charges')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.kdeplot(data=df, x='TotalCharges', hue='Churn', fill=True, common_norm=False, palette='mako')
plt.title('Density Plot of Total Charges by Churn Status')
plt.xlabel('Total Charges')
plt.ylabel('Density')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### Question 7: Do customers with multiple lines or fiber optic internet service have different churn patterns compared to others?

Let's start by analyzing `MultipleLines` in relation to churn.
"""

multiple_lines_churn = df.groupby('MultipleLines')['Churn_Numeric'].mean().reset_index()
multiple_lines_churn['Churn_Rate'] = multiple_lines_churn['Churn_Numeric'] * 100
print("Churn Rate by MultipleLines:")
display(multiple_lines_churn)

plt.figure(figsize=(8, 5))
sns.barplot(x='MultipleLines', y='Churn_Rate', data=multiple_lines_churn, palette='cool')
plt.title('Churn Rate by Multiple Lines Service')
plt.xlabel('Multiple Lines')
plt.ylabel('Churn Rate (%)')
plt.ylim(0, 100)
plt.show()

"""Next, let's re-examine the churn pattern for 'Fiber optic' internet service. We already calculated the churn rate by `InternetService` earlier, but let's highlight the 'Fiber optic' aspect specifically for this question."""

# Re-using the internet_service_churn DataFrame calculated earlier
# If it were not available, we would re-calculate:
# internet_service_churn = df.groupby('InternetService')['Churn_Numeric'].mean().reset_index()
# internet_service_churn['Churn_Rate'] = internet_service_churn['Churn_Numeric'] * 100

print("Churn Rate by Internet Service Type (highlighting Fiber Optic):")
display(internet_service_churn)

plt.figure(figsize=(8, 5))
sns.barplot(x='InternetService', y='Churn_Rate', data=internet_service_churn, palette='viridis')
plt.title('Churn Rate by Internet Service Type')
plt.xlabel('Internet Service Type')
plt.ylabel('Churn Rate (%)')
plt.ylim(0, 100)
plt.show()

"""### Question 9: What payment methods are most commonly used by customers who churn?"""

payment_method_churn = df.groupby('PaymentMethod')['Churn_Numeric'].mean().reset_index()
payment_method_churn['Churn_Rate'] = payment_method_churn['Churn_Numeric'] * 100
print("Churn Rate by Payment Method:")
display(payment_method_churn)

plt.figure(figsize=(10, 6))
sns.barplot(x='PaymentMethod', y='Churn_Rate', data=payment_method_churn, palette='Paired')
plt.title('Churn Rate by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Churn Rate (%)')
plt.ylim(0, 100)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""### Question 10: Is there any noticeable difference in churn rates between male and female customers, or between senior citizens and non-senior citizens?

Let's first analyze the churn rate by `gender`.
"""

gender_churn = df.groupby('gender')['Churn_Numeric'].mean().reset_index()
gender_churn['Churn_Rate'] = gender_churn['Churn_Numeric'] * 100
print("Churn Rate by Gender:")
display(gender_churn)

plt.figure(figsize=(8, 5))
sns.barplot(x='gender', y='Churn_Rate', data=gender_churn, palette='coolwarm')
plt.title('Churn Rate by Gender')
plt.xlabel('Gender')
plt.ylabel('Churn Rate (%)')
plt.ylim(0, 100)
plt.show()

"""Next, let's analyze the churn rate by `SeniorCitizen` status."""

senior_citizen_churn = df.groupby('SeniorCitizen')['Churn_Numeric'].mean().reset_index()
senior_citizen_churn['Churn_Rate'] = senior_citizen_churn['Churn_Numeric'] * 100
print("Churn Rate by Senior Citizen Status:")
display(senior_citizen_churn)

plt.figure(figsize=(8, 5))
sns.barplot(x='SeniorCitizen', y='Churn_Rate', data=senior_citizen_churn, palette='pastel')
plt.title('Churn Rate by Senior Citizen Status')
plt.xlabel('Senior Citizen (0: No, 1: Yes)')
plt.ylabel('Churn Rate (%)')
plt.ylim(0, 100)
plt.xticks(ticks=[0, 1], labels=['No', 'Yes'])
plt.show()