# -*- coding: utf-8 -*-
"""TASK 3 (DATA VISUALIZATION) INTERSHIP CodeAlpha..

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IcXDr8YNlNUiRkQ0bd7a49xTN5uTcvsH

## Load and Display Data
"""

import pandas as pd

df = pd.read_csv('/content/Telco-Customer-Churn.csv')
display(df.head())

"""## Data Exploration and Visualization

Let's first get a general overview of the dataset, including data types and non-null values. This helps in identifying columns that might need cleaning or type conversion.
"""

print(df.info())

"""Next, we'll look at the summary statistics for numerical columns to understand their distribution, central tendency, and spread."""

display(df.describe())

"""### Data Cleaning: Converting 'TotalCharges' and Handling Missing Values"""

# Convert 'TotalCharges' to numeric, coercing errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Check for missing values after conversion
missing_total_charges = df['TotalCharges'].isnull().sum()
print(f"Missing values in 'TotalCharges' after conversion: {missing_total_charges}")

# Handle missing values (e.g., by dropping rows or filling with median/mean)
# For simplicity, let's drop rows with missing 'TotalCharges' for now, as it's a small number
if missing_total_charges > 0:
    df.dropna(subset=['TotalCharges'], inplace=True)
    print("Rows with missing 'TotalCharges' have been dropped.")

# Verify the data type and check for any remaining missing values
print("\nUpdated info for 'TotalCharges' column:")
print(df['TotalCharges'].info())

"""### Data Cleaning: Converting 'TotalCharges' and Handling Missing Values"""

# Convert 'TotalCharges' to numeric, coercing errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Check for missing values after conversion
missing_total_charges = df['TotalCharges'].isnull().sum()
print(f"Missing values in 'TotalCharges' after conversion: {missing_total_charges}")

# Handle missing values (e.g., by dropping rows or filling with median/mean)
# For simplicity, let's drop rows with missing 'TotalCharges' for now, as it's a small number
if missing_total_charges > 0:
    df.dropna(subset=['TotalCharges'], inplace=True)
    print("Rows with missing 'TotalCharges' have been dropped.")

# Verify the data type and check for any remaining missing values
print("\nUpdated info for 'TotalCharges' column:")
print(df['TotalCharges'].info())

"""### Visualizing Churn Distribution"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the aesthetic style of the plots
sns.set_style("whitegrid")

# Create a countplot for the 'Churn' column, addressing the FutureWarning
plt.figure(figsize=(6, 5))
sns.countplot(data=df, x='Churn', hue='Churn', palette='viridis', legend=False)
plt.title('Distribution of Customer Churn')
plt.xlabel('Churn')
plt.ylabel('Number of Customers')
plt.show()

"""### Visualizing Churn Distribution"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the aesthetic style of the plots
sns.set_style("whitegrid")

# Create a countplot for the 'Churn' column
plt.figure(figsize=(6, 5))
sns.countplot(data=df, x='Churn', palette='viridis')
plt.title('Distribution of Customer Churn')
plt.xlabel('Churn')
plt.ylabel('Number of Customers')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Set the aesthetic style of the plots
sns.set_style("whitegrid")

# Create a countplot for the 'Churn' column, addressing the FutureWarning
plt.figure(figsize=(6, 5))
sns.countplot(data=df, x='Churn', hue='Churn', palette='viridis', legend=False)
plt.title('Distribution of Customer Churn')
plt.xlabel('Churn')
plt.ylabel('Number of Customers')
plt.show()

"""### Churn by Gender and SeniorCitizen"""

# Churn by Gender
plt.figure(figsize=(7, 6))
sns.countplot(data=df, x='gender', hue='Churn', palette='viridis')
plt.title('Churn Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Customers')
plt.show()

# Churn by SeniorCitizen
plt.figure(figsize=(7, 6))
sns.countplot(data=df, x='SeniorCitizen', hue='Churn', palette='viridis')
plt.title('Churn Distribution by SeniorCitizen')
plt.xlabel('Senior Citizen (0: No, 1: Yes)')
plt.ylabel('Number of Customers')
plt.show()

"""### Churn by Internet Service and Contract Type"""

# Churn by Internet Service
plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='InternetService', hue='Churn', palette='viridis')
plt.title('Churn Distribution by Internet Service Type')
plt.xlabel('Internet Service')
plt.ylabel('Number of Customers')
plt.show()

# Churn by Contract Type
plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='Contract', hue='Churn', palette='viridis')
plt.title('Churn Distribution by Contract Type')
plt.xlabel('Contract Type')
plt.ylabel('Number of Customers')
plt.show()

"""### Churn by Internet Service and Contract Type"""

# Churn by Internet Service
plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='InternetService', hue='Churn', palette='viridis')
plt.title('Churn Distribution by Internet Service Type')
plt.xlabel('Internet Service')
plt.ylabel('Number of Customers')
plt.show()

# Churn by Contract Type
plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='Contract', hue='Churn', palette='viridis')
plt.title('Churn Distribution by Contract Type')
plt.xlabel('Contract Type')
plt.ylabel('Number of Customers')
plt.show()

"""### Churn by Numerical Features: Tenure, MonthlyCharges, and TotalCharges"""

# Churn distribution by Tenure
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='tenure', hue='Churn', kde=True, palette='viridis')
plt.title('Churn Distribution by Tenure')
plt.xlabel('Tenure (months)')
plt.ylabel('Number of Customers')
plt.show()

# Churn distribution by MonthlyCharges
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='MonthlyCharges', hue='Churn', kde=True, palette='viridis')
plt.title('Churn Distribution by Monthly Charges')
plt.xlabel('Monthly Charges ($)')
plt.ylabel('Number of Customers')
plt.show()

# Churn distribution by TotalCharges
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='TotalCharges', hue='Churn', kde=True, palette='viridis')
plt.title('Churn Distribution by Total Charges')
plt.xlabel('Total Charges ($)')
plt.ylabel('Number of Customers')
plt.show()

"""### Churn by Numerical Features: Tenure, MonthlyCharges, and TotalCharges"""

# Churn distribution by Tenure
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='tenure', hue='Churn', kde=True, palette='viridis')
plt.title('Churn Distribution by Tenure')
plt.xlabel('Tenure (months)')
plt.ylabel('Number of Customers')
plt.show()

# Churn distribution by MonthlyCharges
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='MonthlyCharges', hue='Churn', kde=True, palette='viridis')
plt.title('Churn Distribution by Monthly Charges')
plt.xlabel('Monthly Charges ($)')
plt.ylabel('Number of Customers')
plt.show()

# Churn distribution by TotalCharges
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='TotalCharges', hue='Churn', kde=True, palette='viridis')
plt.title('Churn Distribution by Total Charges')
plt.xlabel('Total Charges ($)')
plt.ylabel('Number of Customers')
plt.show()

"""### Correlation Heatmap of Numerical Features with Churn"""

# Encode 'Churn' column to numerical (0 for No, 1 for Yes) for correlation analysis
df_encoded = df.copy()
df_encoded['Churn_Numeric'] = df_encoded['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

# Select only numerical columns for correlation matrix
numerical_cols = ['tenure', 'MonthlyCharges', 'TotalCharges', 'Churn_Numeric']
correlation_matrix = df_encoded[numerical_cols].corr()

# Plot the heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numerical Features and Churn')
plt.show()

"""### Correlation Heatmap of Numerical Features with Churn"""

# Encode 'Churn' column to numerical (0 for No, 1 for Yes) for correlation analysis
df_encoded = df.copy()
df_encoded['Churn_Numeric'] = df_encoded['Churn'].apply(lambda x: 1 if x == 'Yes' else 0)

# Select only numerical columns for correlation matrix
numerical_cols = ['tenure', 'MonthlyCharges', 'TotalCharges', 'Churn_Numeric']
correlation_matrix = df_encoded[numerical_cols].corr()

# Plot the heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numerical Features and Churn')
plt.show()

"""### Churn by Gender and SeniorCitizen"""

# Churn by Gender
plt.figure(figsize=(7, 6))
sns.countplot(data=df, x='gender', hue='Churn', palette='viridis')
plt.title('Churn Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Customers')
plt.show()

# Churn by SeniorCitizen
plt.figure(figsize=(7, 6))
sns.countplot(data=df, x='SeniorCitizen', hue='Churn', palette='viridis')
plt.title('Churn Distribution by SeniorCitizen')
plt.xlabel('Senior Citizen (0: No, 1: Yes)')
plt.ylabel('Number of Customers')
plt.show()